// Generate src/icons.css: one mask-image class per icon the app actually uses.
//
// Icons are classes, not components, because that is the shape PrimeVue takes
// them in — `<Button icon="…">`, menu items, InputIcon, confirm dialogs all
// accept a class string — so swapping the glyph set never restructures a
// template. Each class paints `currentColor` through a Lucide SVG mask, so an
// icon takes its colour and size from the text around it exactly as a font
// glyph did, in both themes.
//
// The set is whatever `src/` names. Write `aw-icon aw-icon-<lucide name>`
// anywhere, run `npm run icons`, and the class exists; `icons.test.ts` fails
// when a name is used and not generated. Names are Lucide's own
// (https://lucide.dev/icons), so the class says which glyph it draws.
//
//   node scripts/build-icons.mjs          write src/icons.css
//   node scripts/build-icons.mjs --check  exit 1 if it is out of date
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(fileURLToPath(import.meta.url), '../..')
const srcDir = join(root, 'src')
const lucideDir = join(root, 'node_modules/lucide-static/icons')
const outFile = join(srcDir, 'icons.css')

// Modifiers ride on the same prefix but draw nothing.
const MODIFIERS = new Set(['spin'])

// Glyphs Lucide does not have. Lucide is stroke-only; a status dot is a fill.
const CUSTOM = {
  'dot-fill': '<circle cx="12" cy="12" r="6" fill="#000" stroke="none"/>',
}

async function sourceFiles(dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...await sourceFiles(path))
    else if (/\.(vue|ts)$/.test(entry.name)) out.push(path)
  }
  return out
}

async function usedNames() {
  const names = new Set()
  for (const file of await sourceFiles(srcDir)) {
    const text = await readFile(file, 'utf8')
    for (const match of text.matchAll(/(?<![\w-])aw-icon-([a-z0-9]+(?:-[a-z0-9]+)*)/g)) {
      if (!MODIFIERS.has(match[1])) names.add(match[1])
    }
  }
  return [...names].sort()
}

async function glyph(name) {
  if (CUSTOM[name]) return CUSTOM[name]
  let svg
  try {
    svg = await readFile(join(lucideDir, `${name}.svg`), 'utf8')
  } catch {
    throw new Error(`aw-icon-${name}: no Lucide icon named "${name}" (see https://lucide.dev/icons)`)
  }
  const body = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'))
  return body.replace(/\s+/g, ' ').replace(/> </g, '><').trim()
}

function dataUri(inner) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${inner}</svg>`
  return `url("data:image/svg+xml,${svg.replace(/"/g, "'").replace(/[<>#%]/g, encodeURIComponent)}")`
}

const names = await usedNames()
const rules = await Promise.all(names.map(async (name) => `.aw-icon-${name} { --aw-icon-glyph: ${dataUri(await glyph(name))}; }`))
const css = `/* Generated by scripts/build-icons.mjs from lucide-static (ISC). Do not edit:
   name an icon in src/ and run \`npm run icons\`. ${names.length} icons. */
${rules.join('\n')}
`

if (process.argv.includes('--check')) {
  const current = await readFile(outFile, 'utf8').catch(() => '')
  if (current !== css) {
    console.error('src/icons.css is out of date: run `npm run icons`')
    process.exit(1)
  }
} else {
  await writeFile(outFile, css)
  console.log(`src/icons.css: ${names.length} icons`)
}
