"""Saved analyses: create, edit (params/code), execute, remove, and compute.

The working-set sibling of dashboard tiles — same spec-not-data model, but
these live in the Analysis tab's rail. Pinning promotes a copy to a tile via
the existing /tiles routes; the two collections stay independent.

Reading is split by cost on purpose. The collection endpoint lists definitions
and the outcome each one last recorded, and executes nothing. Recomputation
happens only where it was asked for: opening one procedure, or running it.
"""

from __future__ import annotations

import re

from fastapi import APIRouter, Body

from .. import analysis_payloads, analysis_results, workspaces
from .analysis_routes import excel_response

router = APIRouter(prefix="/api/workspaces/{workspace_id}", tags=["analyses"])


@router.get("/analyses")
def get_analyses(workspace_id: str):
    """List saved analyses without running any of them."""
    ws = workspaces.load_workspace(workspace_id)
    return analysis_payloads.analyses_payload(ws)


@router.get("/analyses/summary")
def get_analyses_summary(workspace_id: str):
    """Read persisted execution metadata without re-running any procedure."""
    ws = workspaces.load_workspace(workspace_id)
    return analysis_results.analyses_summary_payload(ws)


@router.get("/analyses/memo")
def get_analysis_memo(workspace_id: str):
    """Read the exploratory-analysis memo and whether it still describes now.

    The memo is derived and read-only: there is no PUT counterpart. It is
    regenerated by requesting ``analysis.summarized``, which is what the
    Summary screen's Regenerate does through the assistant.
    """
    ws = workspaces.load_workspace(workspace_id)
    memo = dict(ws.analysis_summary or {})
    markdown = str(memo.get("markdown") or "")
    basis = analysis_results.summary_basis_digest(ws)
    return {
        "markdown": markdown,
        "cited_analysis_ids": list(memo.get("cited_analysis_ids") or []),
        "generated_at": memo.get("generated_at"),
        "run_id": memo.get("run_id"),
        # Written against a result set that has since moved. The memo is still
        # shown — it is what the analysis concluded at the time — but the
        # screen says so rather than passing it off as current.
        "stale": bool(markdown) and str(memo.get("basis_sha1") or "") != basis,
    }


@router.get("/analyses/{analysis_id}")
def get_analysis(workspace_id: str, analysis_id: str):
    """Recompute one saved analysis for display, without recording a result.

    Opening a procedure shows what its spec returns now. Making that the
    procedure's recorded conclusion is a separate, deliberate act — ``/execute``.
    """
    ws = workspaces.load_workspace(workspace_id)
    return analysis_payloads.analysis_payload(ws, ws._analysis(analysis_id))


@router.post("/analyses/{analysis_id}/preview")
def preview_analysis(workspace_id: str, analysis_id: str, payload: dict = Body(...)):
    """Try an edited spec against the saved input recipe without changing it."""
    ws = workspaces.load_workspace(workspace_id)
    item = dict(ws._analysis(analysis_id))
    if not isinstance(payload.get("spec"), dict):
        raise workspaces.WorkspaceError("Preview requires an analysis spec.")
    item["spec"] = payload["spec"]
    return analysis_payloads.compute_payload(ws, item)


@router.get("/analyses/{analysis_id}/exceptions")
def get_analysis_exceptions(workspace_id: str, analysis_id: str):
    """Read back the rows the recorded result flagged, without recomputing.

    This is deliberately not the detail endpoint. Opening a procedure asks
    "what does this spec return now"; this asks "which rows did the conclusion
    on record concern" — the question a reviewer reading a verdict actually
    has. It costs a file read rather than a Polars run, and it cannot show rows
    that disagree with the verdict printed beside them.
    """
    ws = workspaces.load_workspace(workspace_id)
    analysis = ws._analysis(analysis_id)
    evidence = analysis_results.read_exception_evidence(ws, analysis)
    result = analysis.get("last_result") or {}
    return {
        "analysis_id": analysis_id,
        "exception_count": int(result.get("exception_count") or 0),
        "retained": int(result.get("exception_rows_retained") or 0),
        "run_id": result.get("run_id"),
        "executed_at": result.get("executed_at"),
        "frame": (evidence or {}).get("frame"),
    }


@router.post("/analyses/{analysis_id}/execute")
def execute_analysis(workspace_id: str, analysis_id: str):
    """Run one saved analysis and record what it concluded.

    This is the auditor's counterpart to the workflow's execution capability,
    and it writes the same bounded result contract — so a procedure the auditor
    ran is as current, and as reviewable, as one the agent ran.
    """
    ws = workspaces.load_workspace(workspace_id)
    executed = analysis_results.execute_and_record(ws, analysis_id)
    # Same shape as the detail endpoint, carrying the rows this execution
    # produced rather than recomputing them a second time to say so.
    return {
        **analysis_payloads.analysis_payload(ws, executed.analysis, computed=executed.payload),
    }


@router.post("/analyses/execute")
def execute_analyses(workspace_id: str, payload: dict = Body(default={})):
    """Execute several saved analyses in one pass.

    ``ids`` names them explicitly; otherwise every procedure whose result is
    missing or stale is brought current, which is what "rerun what needs it"
    means on the Analysis tab. Each execution is committed on its own, so one
    broken spec neither blocks nor rolls back the others.
    """
    ws = workspaces.load_workspace(workspace_id)
    requested = [str(value) for value in (payload.get("ids") or []) if str(value or "").strip()]
    if not requested:
        requested = [
            str(item.get("id"))
            for item in ws.analyses
            if analysis_results.analysis_result_state(ws, item) != "current"
        ]
    executed: list[dict] = []
    for analysis_id in requested:
        try:
            outcome = analysis_results.execute_and_record(ws, analysis_id)
        except workspaces.WorkspaceError as error:
            executed.append({"analysis_id": analysis_id, "ok": False, "error": str(error)})
            continue
        executed.append(
            {
                "analysis_id": analysis_id,
                "ok": True,
                "title": outcome.analysis.get("title"),
                "result": outcome.result,
            }
        )
    return {
        "executed": executed,
        "summary": analysis_results.analyses_summary_payload(ws),
    }


@router.post("/analyses")
def add_analysis(workspace_id: str, payload: dict = Body(...)):
    ws = workspaces.load_workspace(workspace_id)
    analysis = ws.add_analysis(payload)
    return analysis_payloads.analysis_payload(ws, analysis)


@router.patch("/analyses/{analysis_id}")
def update_analysis(workspace_id: str, analysis_id: str, changes: dict = Body(...)):
    ws = workspaces.load_workspace(workspace_id)
    analysis = ws.update_analysis(analysis_id, changes)
    return analysis_payloads.analysis_payload(ws, analysis)


@router.post("/analyses/{analysis_id}/export")
def export_analysis(workspace_id: str, analysis_id: str):
    """Stream one saved analysis' full result as a workbook.

    Both kinds export the same way, so a hand-written Polars procedure is as
    exportable as a library test — the earlier split left python analyses with
    no way off the screen at all.
    """
    ws = workspaces.load_workspace(workspace_id)
    analysis = ws._analysis(analysis_id)
    frame = analysis_payloads.analysis_export_frame(ws, analysis)
    name = re.sub(r"[^A-Za-z0-9._-]+", "_", str(analysis.get("title") or analysis_id))
    return excel_response(frame, f"{name}.xlsx")
@router.delete("/analyses/{analysis_id}")
def remove_analysis(workspace_id: str, analysis_id: str):
    ws = workspaces.load_workspace(workspace_id)
    ws.remove_analysis(analysis_id)
    return {"ok": True}
